### PR TITLE
force xhci usb mode on steam deck to workaround firmware bug

### PR DESCRIPTION
**Pull request by alkazar**
this allows booting on steam deck with external usb devices, particularly important for the installer

### CODE REVIEW

**Comment by pastaq** [comment]
What is the source? I'd like to maintain credit in the git history.

**Comment by alkazar** [comment]
This is the information I have:
```
commit c99f302ea6799cc52517023d78754483475262a1
Author: Vicki Pfau <vi@endrift.com>
Date:   Wed Sep 27 13:22:12 2023 -0700

    PCI: Prevent xHCI driver from claiming AMD VanGogh USB3 DRD device
    
    commit 7e6f3b6d2c352b5fde37ce3fed83bdf6172eebd4 upstream.
```

How do we incorporate that information?

**Comment by alkazar** [comment]
Updated the commit author.

**Comment by BoukeHaarsma23** [comment]
Needs to be on top of 6.6 I guess?

**Comment by alkazar** [comment]
> Needs to be on top of 6.6 I guess?

6.6 is for stable, right? I am not sure if we want to include it there, but in any case, I want to add it to unstable first and test it.

**Comment by Samsagax** [comment]
@alkazar is this one still relevant? If so, can it be rebased against current stable (6.10 at this time)?

**Comment by alkazar** [comment]
Yes, I think it is still relevant. I will try rebasing.

**Comment by Samsagax** [comment]
I added it to v6.9.12-chos7. Should be in v46-2 when it comes out

**Pull request closed without merging**
