### PR TITLE
Updated AW87xxx driver to automatically enumerate a second I2C chip

### PR DESCRIPTION
**Pull request by CVMagic**
Only if specified in ACPI.

Sorry for the large Diff, realized I was using a dos formatted file, switched back to unix.

### CODE REVIEW

**Comment by BoukeHaarsma23** [comment]
I will try to retarget to 6.9 if you don't mind :)

**Comment by BoukeHaarsma23** [comment]
Meh, github is stupid. I will try to merge it manually into 6.9

**Comment by CVMagic** [comment]
I can resubmit the PR for 6.9, I didnt realize we had already switched.

**Comment by BoukeHaarsma23** [comment]
I'm already rebasing, no need :) I'll ping you when it's done

**Comment by BoukeHaarsma23** [comment]
6c957c3caa8a555e5f07e78cf0592bbbd103c9e0 includes this

**Pull request closed without merging**
